[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "API Documentation"
authors = [{name = "Michael", email = "Michael@bfore.ai"}]
dynamic = ["version", "description"]